{{- if not .Values.base64 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.common.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
  annotations:
    {{- if .Values.avp_path }}
    avp_path: {{ .Values.avp_path }}
    {{- end }}
    {{- if .Values.controller.podAnnotations }}
    {{- with .Values.controller.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
type: Opaque
stringData:
  {{- if .Values.nats.auth.password }}
  NATS__PASSWORD: {{ .Values.nats.auth.password }}
  {{- end }}
{{- end }}