FROM quay.io/diem/base-pyspark:3.0.0

COPY db2-jars/* /opt/spark/jars/
COPY stocator/* /opt/spark/jars/

WORKDIR /opt/

# For spark 3 we need t install them as root and then switch back

USER root

RUN python3.7 -m pip install --upgrade pip

COPY requirements.txt $HOME
RUN python3.7 -m pip install -r requirements.txt

RUN chmod -R 775 .

# USER 185


