before_install:
  - conveyor artifactory init -s sets

install:
  - npm ci

script:
  - npm run build

deploy:
  - conveyor release -a "sets" -c etl-angular-util -p -t npm -m packages/etl-angular-util
