name: CI - Changelog

on:
  push:
    branches: [main]
    paths-ignore:
      - "CHANGELOG.md"

jobs:
  changelog_prerelease:
    name: Update Changelog For Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.PAT }}
      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          bugLabels: "fix,bug"
          unreleasedOnly: true
          enhancementLabels: "chore,style"
          addSections: '{"documentation":{"prefix":"**Documentation:**","labels":["documentation"]}}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog for PR
          push_options: --force
          file_pattern: CHANGELOG.md
