# This is a basic workflow to help you get started with Actions

name: CI diem-common

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths:
      - "packages/diem-common/**"
  pull_request:
    branches: [main]
    paths:
      - "packages/diem-common/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/diem-common

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"

      - run: npm ci
      - run: npm run eslint --if-present
      - run: npm run build --if-present

      - name: Deploy to NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{secrets.NPM_TOKEN}}
          npm publish --ignore-scripts --access public
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' )
